name: Deploy custom pyodide build to Github registry (@ozobot)

on:
  push:
    tags:
      - 'ozobot/**'

jobs:
  run_main:
    uses: ./.github/workflows/main.yml

  check-version:
    # TODO: this job should cancel the `run_main` on failure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Compare tag with pyodide version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/*}
          TAG_VERSION="${TAG_NAME##ozobot/}"
          PACKAGE_VERSION=$(jq -r '.version' ./src/js/package.json)
          if [[ "$PACKAGE_VERSION" != "$TAG_VERSION" ]]
          then
            >&2 echo "Version derived from tag name (${TAG_NAME}) does not match version in 'src/js/package.json' file (${PACKAGE_VERSION})"
            >&2 echo "Cancelling the deploy, as the tag and package version are out of sync."
            exit 1
          fi

  publish-npm-package:
    runs-on: ubuntu-latest
    needs: [check-version, run_main]
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: core-build-Linux
          path: ./

      - uses: actions/setup-node@v4
        name: Setup npm for packaging
        with:
          node-version: '18.x'
          #note: it seems the `registry-url` is not honored, so we define it in package.json's publishConfig again
          registry-url: 'https://npm.pkg.github.com'

      
      - name: Install npm deps
        run: npm install
      
      - name: Publish npm package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
