name: Deploy custom pyodide build to Github registry (@ozobot)

on:
  push:
    tags:
      - 'ozobot/**'

jobs:
  run_main:
    uses: ./.github/workflows/main.yml

  publish-npm-package:
    runs-on: ubuntu-latest
    needs: run_main
    steps:
      - uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: core-build-Linux
          path: ./

      - uses: actions/setup-node@v4
        name: Setup npm for packaging
        with:
          node-version: '18.x'
          #note: it seems the `registry-url` is not honored, so we define it in package.json's publishConfig again
          registry-url: 'https://npm.pkg.github.com'

      
      - name: Install npm deps
        run: npm install
      
      - name: Publish npm package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
